#!/bin/bash

# Check if the languagetool server is running
if ps -eo pid,cmd | grep '[l]anguagetool-commandline.jar' > /dev/null; then
  # End dictation if active
  ~/.config/eww/scripts/toggle-dictation off
  # End languagetool server
  ps -eo pid,cmd | grep '[l]anguagetool-commandline' | awk '{print $1}' | xargs kill
  # Close the dictation widget
  eww close dictation
else
  # Notify if languagetool server was not running (something went wrong)
  notify-send 'Dictation Error - languagetool server not found'
fi
